-- AlterTable
ALTER TABLE "Site" DROP COLUMN IF EXISTS "name",
DROP COLUMN IF EXISTS "jobTitle",
DROP COLUMN IF EXISTS "summary",
DROP COLUMN IF EXISTS "experience",
DROP COLUMN IF EXISTS "education",
DROP COLUMN IF EXISTS "skills",
DROP COLUMN IF EXISTS "languages",
DROP COLUMN IF EXISTS "email",
DROP COLUMN IF EXISTS "phone",
DROP COLUMN IF EXISTS "location",
DROP COLUMN IF EXISTS "linkedinUrl",
DROP COLUMN IF EXISTS "githubUrl";
