-- AlterTable
ALTER TABLE "User" ADD COLUMN     "editsResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "editsThisMonth" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "planType" TEXT NOT NULL DEFAULT 'FREE',
ADD COLUMN     "recreatesResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "recreatesThisMonth" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "storageLimit" BIGINT NOT NULL DEFAULT 104857600,
ADD COLUMN     "storageUsed" BIGINT NOT NULL DEFAULT 0;
