/**
 * Site component template'leri için tip tanımları
 */

export interface ThemeColors {
  // Base colors (selected by Gemini or user)
  primary: string;
  secondary: string;
  accent: string;
  neutral: string;

  // Derived colors (auto-generated from base colors)
  background: string;
  surface: string;
  text: string;
  textSecondary: string;
  border: string;
  hover: string;
  iconPrimary: string;
  iconSecondary: string;

  // Font properties
  fontHeading?: string;
  fontBody?: string;
}

export interface ComponentTemplate {
  id: string;
  name: string;
  category: 'navigation' | 'hero' | 'experience' | 'education' | 'portfolio' | 'skills' | 'languages' | 'contact' | 'footer';
  iconStyle?: 'outline' | 'solid'; // Icon style for this template
  htmlTemplate: string;
  cssTemplate: string;
  jsTemplate?: string;
  placeholders?: string[];
  dataSchema?: {
    [key: string]: {
      type: string;
      required: boolean;
      description: string;
    };
  };
  designNotes?: string;
}

export interface SelectedComponent {
  category: string;
  templateId: string;
}

export interface SiteGenerationPlan {
  themeColors: ThemeColors;
  theme: 'light' | 'dark';  // Light or dark theme
  selectedComponents: SelectedComponent[];
  layout: 'single-page' | 'multi-page';
  style: 'modern' | 'minimal' | 'creative' | 'professional';
  iconStyle?: 'outline' | 'solid';
  iconSizes?: {
    navigation: string;
    social: string;
  };
  fontStyle?: 'modern' | 'professional' | 'creative' | 'minimal';
  fontPairId?: string;

  /** Stok fotoğraf bilgileri (hotlinking için URL'ler) */
  stockImages?: {
    [category: string]: {
      url: string;
      alt: string;
      photographer?: string;
      pexelsId?: number;
      avgColor?: string;
    };
  };

  /** SEO metadata generated by AI */
  seoData?: SEOData;
}

/**
 * SEO metadata for generated sites
 */
export interface SEOData {
  /** Optimized page title (e.g., "John Doe - Software Engineer | Portfolio") */
  metaTitle: string;
  /** SEO-friendly description (150-160 characters) */
  metaDescription: string;
  /** Keywords extracted from CV (5-10 items) */
  keywords: string[];
  /** Short professional summary for JSON-LD structured data */
  professionalSummary?: string;
}
